### ISSUE TITLE
doesnot work

### ISSUE THREAD

**Issue by Jasi2169** [rednaga/DexHook#2]
hello it doesnot seems to work on android 6.0 and then tried on android 4.1.2 no output comes up,don ot know why the output stream is not bringing anything
i was looking if we can reverse the android dumped memory to dex or something ?

**Comment by CunningLogic** [comment]
Tested  on 6.0 AOSP/Nexus, seems to work fine. You may have to disable selinux to use it

**Comment by Jasi2169** [comment]
well SELinux fixed this thought xposed can hook any processes this selinux is crazy

**Comment by CunningLogic** [comment]
selinux can not hook any process, it can hook dalvik processes, selinux operates in the context of the kernel.

**Comment by Jasi2169** [comment]
hmm quite interesting well got the class loading dexguard seems loads one by one when required  
but the fact remains it didnot worked for me on jelly bean 4.1.2 when had no selnux thing anyway who cares work on 6.0.1

**Comment by henrytom1703** [comment]
Hello @Jasi2169 @CunningLogic 
Can you guide me how to loads native shared libs into other apps with xposed?
Thanks

**Comment by strazzere** [comment]
@henrytom1703 This really has nothing to do with loading native shared libs. To do that, all you'd need to do is get the app to perform a `loadlibrary` call. Alternatively you could also just do a type of `LD_PRELOAD` into it (using the setprop method or something)
